config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  # get 'order_items/create'
  # get 'order_items/update'
  # get 'order_items/destroy'
  devise_for :users
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
 
   
 as :user do
  get "signin" => "devise/sessions#new"
  post "signin" => "devise/sessions#create"
  delete "signout" => "devise/sessions#destroy"
 end
 

 resources :items do 
  resources :reviews
 end


 
 
 
  
 resources :conversations do
   resources :messages
 end

 resources :ur_stores

 resources :categories

 resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
  

    def add_item(item)
        current_item = line_items.find_by(item_id: item.id)
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(item_id: item.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum{ |item| item.total_price}
    end
    
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items

end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender,  :foreign_key => :sender_id , class_name: 'User'
    belongs_to :recipent, :foreign_key => :recipent_id, class_name: 'User'

    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, :scope => :recipent_id
    
    scope :involving, -> (user) do
        where("conversations.sender_id =? OR conversations.recipent_id =?", user.id, user.id )  
    end 

    scope :between, -> (sender_id, recipent_id) do
        where("(conversations.sender_id =? AND conversations.recipent_id =?) OR (conversations.sender_id =? AND conversations.recipent_id = ?)",sender_id, recipent_id, recipent_id, sender_id)
    end
end
 

app/models/item.rb
class Item < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    belongs_to :ur_store, optional: true
    belongs_to :category
    has_many :line_items
    has_one :user, through: :store
    has_many :reviews
    
    
    has_attached_file :item_img, styles: { item_index: "250x350>", item_show: "325x475>"}
    validates_attachment_content_type :item_img, content_type: /\Aimage\/.*\Z/

    default_scope { where(active: true) }

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "line items present!")
            throw :abort
        end      
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart


  def total_price
      item.price.to_i * quantity.to_i
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id 
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :item
    belongs_to :user
end

app/models/ur_store.rb
class UrStore < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_one :ur_store
  has_many :items , through: :store
  has_many :reviews
  has_many :orders, dependent: :destroy

  has_many :conversations, :foreign_key => :sender_id

  has_one_attached :avatar
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id  == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to items_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to items_path, notice: "That cart doesn't exist"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper  
    
   def cart_count_over_one
      return total_cart_items if total_cart_items > 0
   end

   def total_cart_items
      total =  @cart.line_items.map(&:quantity).sum
      return total if total > 0
   end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

    def self_or_other(message)
        message.user == current_user ? "self" : "other"
    end

    def message_interlocutor(message)
        message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipent
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
    def calc_price unit_price, quantity
        unit_price * quantity.to_i
      end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ur_stores_helper.rb
module UrStoresHelper

    def current_user?
        self == current_user 
    end

    def verify_store?
        current_user.ur_store != nil    
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def conversation_interlocutor(conversation)
        conversation.recipent == current_user ? conversation.sender : conversation.recipent
    end 
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/_order_cart.html.erb
<tr>
  <td class="cart_product">
    <%= link_to order_item.item do %>
    <% end %>
  </td>
  <td class="cart_description">
    <p class="item-name">
      <%= link_to order_item.item do %>
        <%= order_item.item_name %>
      <% end %>
    </p>
  </td>
  <td class="price"><span><%= order_item.item_price %></span></td>
  <td class="qty">
    <%= form_tag cart_path(item_id: order_item.item_id), method: :patch do %>
      <%= number_field_tag :quantity, nil, class: "form-control input-sm",
        min: 1, max: order_item.item_quantity,
        value: order_item.quantity %> <br />
      <%= button_tag type: "submit", class: "btn", name: nil do %>
        <%= content_tag :span, t(".apply") %>
      <% end %>
    <% end %>
  </td>
  <td class="price">
    <span>
      <%= calc_price order_item.item_price, order_item.quantity %>
    </span>
  </td>
  <td class="action">
    <%= link_to cart_path(item_id: order_item.item_id), method: :delete,
      data: {confirm: t(".you_sure")} do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </td>
</tr>

app/views/carts/_shopping_cart.html.erb
<div class="order-detail-content">
  <div class="table-responsive">
    <table class="table table-bordered cart_summary">
      <thead>
        <tr>
          <th><%= t ".product" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".price" %></th>
          <th><%= t ".quantity" %></th>
          <th><%= t ".total_label" %></th>
          <th><%= t ".function" %></th>
        </tr>
      </thead>
      <tbody>
        <% if @order_items.any? %>  
          <%= render partial: "order_cart", collection: @order_items, as: :order_item %>
        <% else %>
          <tr><td colspan="6"><%= t ".no_item" %></td></tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2" rowspan="2"></td>
          <td colspan="3"><strong><%= t ".total_label" %></strong></td>
          <td colspan="2">
            <strong id="cart-total-price">
              <%= t ".total", price: total_price(@order_items) %>
            </strong>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
  <div class="cart_navigation">
    <% if @order_items.any? %>
      <%= link_to orders_path, class: "checkout-btn", method: :post do %>
        <i class="fa fa-check"></i><%= t ".checkout" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/carts/create.js.erb
if('<%= flash.blank? %>' != 'true') {
  $('.alert').addClass('alert-success').text('<%= flash[:success] %>').show();
  $('span.cart-total').text("<%= t "layouts.navbar.items", item: current_order.size %>")
  $(document).ready(function() {
    setTimeout(function() {
      $(".alert").fadeOut(2000);
    }, 3000);
  });
}

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class = "keep-shopping pv1 mt4 has-text-right">
    <%= link_to 'Keep shopping', items_path, class: 'btn is-warning'  %>
</div>

<section class= "section">
   <%= render(@cart.line_items) %>

   
   <div class = "columns">
       <div class = "column">
           <%= button_to 'Empty cart', @cart, method: :delete, data: {confirm: "Are you sure?"},
               class: "btn is-danger" %>
       </div>
       <div class="column total has-text-right" >
           <h4 class ="title is-4">
              <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
           </h4>
       </div>
   </div>
</section>