config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  # get 'order_items/create'
  # get 'order_items/update'
  # get 'order_items/destroy'
  devise_for :users
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
 
   
 as :user do
  get "signin" => "devise/sessions#new"
  post "signin" => "devise/sessions#create"
  delete "signout" => "devise/sessions#destroy"
 end
 

 resources :items do 
  resources :reviews
 end


 
 
 
  
 resources :conversations do
   resources :messages
 end

 resources :ur_stores

 resources :categories

 resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
  

    def add_item(item)
        current_item = line_items.find_by(item_id: item.id)
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(item_id: item.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum{ |item| item.total_price}
    end
    
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items

end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender,  :foreign_key => :sender_id , class_name: 'User'
    belongs_to :recipent, :foreign_key => :recipent_id, class_name: 'User'

    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, :scope => :recipent_id
    
    scope :involving, -> (user) do
        where("conversations.sender_id =? OR conversations.recipent_id =?", user.id, user.id )  
    end 

    scope :between, -> (sender_id, recipent_id) do
        where("(conversations.sender_id =? AND conversations.recipent_id =?) OR (conversations.sender_id =? AND conversations.recipent_id = ?)",sender_id, recipent_id, recipent_id, sender_id)
    end
end
 

app/models/item.rb
class Item < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    belongs_to :ur_store, optional: true
    belongs_to :category
    has_many :line_items
    has_one :user, through: :store
    has_many :reviews
    
    
    has_attached_file :item_img, styles: { item_index: "250x350>", item_show: "325x475>"}
    validates_attachment_content_type :item_img, content_type: /\Aimage\/.*\Z/

    default_scope { where(active: true) }

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "line items present!")
            throw :abort
        end      
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart


  def total_price
      item.price.to_i * quantity.to_i
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id 
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :item
    belongs_to :user
end

app/models/ur_store.rb
class UrStore < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_one :ur_store
  has_many :items , through: :store
  has_many :reviews
  has_many :orders, dependent: :destroy

  has_many :conversations, :foreign_key => :sender_id

  has_one_attached :avatar
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :find_item, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    # before_action :find_store
    def index
        if params[:category].blank?
            @items = Item.all.order("created_at DESC")
        end    
        
        if params[:category]
            
            @category_id = Category.find_by(name: params[:category]).id
            
            @items = Item.where(category_id: @category_id).order("created_at DESC")
        end

   
    end
    
    

    def show
    
        if @item.reviews.blank?
            @average_review = 0
        else  
            @average_review = @item.reviews.average(:rating).round(2)  
        end

    end

    def new
        # @item = Item.new
        @ur_store = current_user.ur_store
        @item = @ur_store.items.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
       
        
    end
    
    

    def update
         @item.category_id = params[:category_id]
        if @item.update(item_params)
            redirect_to item_path(@item)
        else 
            render 'edit'
        end
    end

    def create
        @ur_store = current_user.ur_store 
        @item = @ur_store.items.build(item_params)
        @item.category_id = params[:category_id]
        if @item.save
           flash[:success] = "Creating item success"
           redirect_to @item    
        else
            render 'new'
        end
    end

    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def destroy
        return unless @item.destroy
        redirect_to items_path
    end
    
    def sort 
        if params[:items]
            @items_request = convert params[:items].values
            respond_to do |format|
                format.html
                format.js
            end
        end
    
    end

    def convert arr 
        newArr = []
        arr.each do |object|
            newMyObject = Item.new(object)
            newArr<<newMyObject
        end
        return newArr 
    end


    private

    def item_params
        params.require(:item).permit(:code, :name, :description, :producer, :item_img, :ur_store_id,
        :category_id  )
    end
    
    def find_item
        @item = Item.find(params[:id])
    end

    def find_store
        @ur_store = Item.find(params[:ur_store_id])
    end

    def find_user
        @user = User.find_by(params[:user_id]) 
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper  
    
   def cart_count_over_one
      return total_cart_items if total_cart_items > 0
   end

   def total_cart_items
      total =  @cart.line_items.map(&:quantity).sum
      return total if total > 0
   end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

    def self_or_other(message)
        message.user == current_user ? "self" : "other"
    end

    def message_interlocutor(message)
        message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipent
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
    def calc_price unit_price, quantity
        unit_price * quantity.to_i
      end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ur_stores_helper.rb
module UrStoresHelper

    def current_user?
        self == current_user 
    end

    def verify_store?
        current_user.ur_store != nil    
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def conversation_interlocutor(conversation)
        conversation.recipent == current_user ? conversation.sender : conversation.recipent
    end 
end

app/views/items/_form.html.erb
<%= form_for (@item), :html => { :multipart => true }  do |f|  %>
 <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select add category") %><br />
 <%= f.file_field :item_img %>
 <%= f.label :code %>
 <%= f.text_field :code, class: "form-control"%>
 <%= f.label :name %>
 <%= f.text_field :name, class: "form-control"%>
 <%= f.label :description %>
 <%= f.text_field :description, class: "form-control" %>
 <%= f.label :producer %>
 <%= f.text_field :producer, class: "form-control"%>
 <%= f.submit "Create", class: "btn btn-primary" %>
 
<% end %>

app/views/items/_item_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
        <h2 class = "item-title">name:     <%= @item.name %> </h2>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency item.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :item_id, value: item.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/items/_show_review.html.erb
<script>
   	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>


<script>
 $('.review-rating').raty({
   readOnly: true,
   path: '/assets/', 
   score: function() {
     return $(this).attr('data-score');
   }
 });
</script>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= simple_form_for @item, :html => { :multipart => true } do |f|  %>
 <%= f.select :category_id, @categories %>
 <%= f.file_field :item_img %>
 <%= f.input :code, label: "Code" %>
 <%= f.input :name %>
 <%= f.input :description %>
 <%= f.input :producer %>
 <%= f.button :submit %>
<% end %>

app/views/items/index.html.erb
<%
=begin%>
 <h1 class="current-category"><%= params[:category] %></h1>
<% if @items.count == 0 %>
  <h1>Don't have any items in this categories</h1>
<% else %>
   <div class = "row">
     <% @items.each do |item| %>
      
     <div class= "col-md-3">
        <a href = "/items/<%= item.id %>">
          <%= image_tag item.item_img.url(:item_index), class: "item" %>
        </a> 
     </div>

     
     <% end %>
   </div>
<% end %> 
<%
=end%>


 

 

 
<body class="woocommerce">
  
    <ul class="mystyle-products">
    <% if @items.count == 0 %>
          <h1>Don't have any items in this categories</h1>
    <% else %>
       <% @items.each do |item| %>
      <li class="product">
            <a href = "/items/<%= item.id %>">
            <%= image_tag item.item_img.url(:item_index),class: "item" %>
            </a>       
          <h2><%= link_to item.name, item_path(item) %></h2>
          
          <span class="price">
            <ins> <span class="amount"><%= item.price %></span> </ins>
          </span>
        
        <button class="button_index" rel="nofollow" href="#">
         Add to cart
        </button>
      </li>        
      <% end %>  
    <%end %>  
    </ul>
</body>

  

app/views/items/new.html.erb
<h1> Let's create! </h1>

<%= render 'form'%>

app/views/items/show.html.erb
<div class= "row">
  <div class="col-md-4">
  <%= image_tag @item.item_img.url(:item_show), class: "item-show" %>
  </div>
  
  <div class="col-md-8">
    <div class= "item-info">
     
    
     
     <h3 class = "item-producer">From: <%=link_to @item.ur_store.name, ur_store_path(@item.ur_store.id) %></h3>
     <h3 class = "item-producer">Producer: <%= @item.producer %> </h3>
     
     <h2>Avarage rating</h2>
     <div class= "average-review-rating" data-score=<%= @average_review %>></div>
     <span class ="number-of-reviews">Based on <%= @item.reviews.count %> reviews</span>
     <h4>Category: <%= @item.category.name%> </h4> 
     <h5>Price:    <%= @item.price %></h5>
     <%= button_to "Add to cart" ,line_items_path(item_id: @item) , class: 'btn btn-success'%>
     <p class= "item-desc"><%= @item.description %></p>
     
    <h2> see more product from<%= link_to @item.ur_store.name, ur_store_path(@item.ur_store.id)   %></h2> 

=end%>
  </div>
   
  

</div>



<div class = "row">
  <div class = "col-md-4">
    <div class ="reviews">
       <div id = 'new-review'>
          <%= render @item.reviews %>
       </div>
    </div>
  </div>
</div>
<h2>Add review</h2>
<%= render "reviews/form" %>





<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

<script>
 $('.review-rating').raty({
   readOnly: true,
   path: '/assets/', 
   score: function() {
     return $(this).attr('data-score');
   }
 });
</script>