config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  # get 'order_items/create'
  # get 'order_items/update'
  # get 'order_items/destroy'
  devise_for :users
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
 
   
 as :user do
  get "signin" => "devise/sessions#new"
  post "signin" => "devise/sessions#create"
  delete "signout" => "devise/sessions#destroy"
 end
 

 resources :items do 
  resources :reviews
 end


 
 
 
  
 resources :conversations do
   resources :messages
 end

 resources :ur_stores

 resources :categories

 resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
  

    def add_item(item)
        current_item = line_items.find_by(item_id: item.id)
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(item_id: item.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum{ |item| item.total_price}
    end
    
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items

end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender,  :foreign_key => :sender_id , class_name: 'User'
    belongs_to :recipent, :foreign_key => :recipent_id, class_name: 'User'

    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, :scope => :recipent_id
    
    scope :involving, -> (user) do
        where("conversations.sender_id =? OR conversations.recipent_id =?", user.id, user.id )  
    end 

    scope :between, -> (sender_id, recipent_id) do
        where("(conversations.sender_id =? AND conversations.recipent_id =?) OR (conversations.sender_id =? AND conversations.recipent_id = ?)",sender_id, recipent_id, recipent_id, sender_id)
    end
end
 

app/models/item.rb
class Item < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    belongs_to :ur_store, optional: true
    belongs_to :category
    has_many :line_items
    has_one :user, through: :store
    has_many :reviews
    
    
    has_attached_file :item_img, styles: { item_index: "250x350>", item_show: "325x475>"}
    validates_attachment_content_type :item_img, content_type: /\Aimage\/.*\Z/

    default_scope { where(active: true) }

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "line items present!")
            throw :abort
        end      
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart


  def total_price
      item.price.to_i * quantity.to_i
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id 
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :item
    belongs_to :user
end

app/models/ur_store.rb
class UrStore < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_one :ur_store
  has_many :items , through: :store
  has_many :reviews
  has_many :orders, dependent: :destroy

  has_many :conversations, :foreign_key => :sender_id

  has_one_attached :avatar
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_category, only: [:show, :update, :edit, :destroy]

    def index
      @q =Category.ransack(params[:id])
      @categories = @q.result.order("created_at DESC").page(params[:page])
     
      respond_to do |format|
            format.html
            format.js
        end 
    end

    def show
        
      # @items = @category.items
      @items = Item.where(category_id: @category.id)    
    end

    def new
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
        if @category.save
            flash[:info] = "Adding Category Success!"
            redirect_to action: "index"
        else    
            redirect_to new
        end
    end

    def edit; end
    

  def update
    if @category.update_attributes(category_params)
      flash[:success] = "Category updated"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
        format.js
    end
  end

  private 
  
  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  
    
   def cart_count_over_one
      return total_cart_items if total_cart_items > 0
   end

   def total_cart_items
      total =  @cart.line_items.map(&:quantity).sum
      return total if total > 0
   end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

    def self_or_other(message)
        message.user == current_user ? "self" : "other"
    end

    def message_interlocutor(message)
        message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipent
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
    def calc_price unit_price, quantity
        unit_price * quantity.to_i
      end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ur_stores_helper.rb
module UrStoresHelper

    def current_user?
        self == current_user 
    end

    def verify_store?
        current_user.ur_store != nil    
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def conversation_interlocutor(conversation)
        conversation.recipent == current_user ? conversation.sender : conversation.recipent
    end 
end

app/views/categories/_category.html.erb
<li>
  <%= link_to "#{category.name}(#{category.items.count})", category %>
  <% if user_signed_in? && current_user.role ==1  %>
  	<span >
    	<%= link_to "Edit", edit_category_path(category), class: "btn btn-primary edit"%>
    	<%= link_to "Delete", category, method: :delete,
                                     data: { confirm: "You sure?", remote: true },class: "delete_categories btn btn-primary delete" %>
  	</span>
  <% end %>
</li>

app/views/categories/_excel.html.erb
<p>
	<h3 style="text-align: center;"><%= link_to "EXCEL", categories_path(format: "xls"), class: "glyphicon glyphicon-save" %></h3>
</p>

app/views/categories/_item.html.erb
<li class="col-12 col-md-6 col-lg-3" style="padding: 50px 0px"> 
   
  <div class="cnt-block equal-hight" style="height: 349px;">
      <figure>
      	<a href="/items/<%= item.id %>">
      		<%= image_tag item.item_img.url(:item_index), class: "item"%>
      	</a>
      </figure>
      <p><%= link_to item.name , item,%></p>
	  <ul class="follow-us clearfix">
	  	
	  </ul>
  </div>
</li>

app/views/categories/destroy.js.erb
$('.delete_categories').bind('ajax:success', function() {
      $(this).closest('li').fadeOut();
});

app/views/categories/edit.html.erb
<h1>Update category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/categories/index.html.erb
<% provide(:title, "Category") %>
<h1>List Category</h1>
<%= render "shared/search"%>
<% if user_signed_in? && current_user.role == 1  %>
	<div> 
    	<h3 style="text-align: center;"><%= link_to "CATEGORY", new_category_path, class: "glyphicon glyphicon-plus"%></h3>
    	<span><%=render "excel" %></span>
  	</div>
<%end%>


<ul class="categories">
   <%= render @categories %>
</ul>

app/views/categories/new.html.erb
<h1>Create new category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Create new category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/categories/show.html.erb
<% provide :title, @category.name %>
<h1><%= @category.name+"(#{@category.items.count})" %></h1>

<div>
  <%
=begin%>
 <ul class="row">
       <%= render @items %>     
  </ul>  
<%
=end%>

<body class="woocommerce">
  
    <ul class="mystyle-products">
    <% if @items.count == 0 %>
          <h1>Don't have any items in this categories</h1>
    <% else %>
       <% @items.each do |item| %>
      <li class="product">
            <a href = "/items/<%= item.id %>">
            <%= image_tag item.item_img.url(:item_index),class: "item" %>
            </a>       
          <h2><%= link_to item.name, item_path(item) %></h2>
          
          <span class="price">
            <ins> <span class="amount"><%= item.price %></span> </ins>
          </span>
        
        <button class="button_index" rel="nofollow" href="#">
         Add to cart
        </button>
      </li>        
      <% end %>  
    <%end %>  
    </ul>
</body>
</div>